# Generated by Django 3.1.7 on 2021-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('deal_code', models.CharField(max_length=255)),
                ('customer_code', models.IntegerField()),
                ('service_code', models.CharField(max_length=255)),
                ('promotion_code', models.CharField(max_length=255)),
                ('pay_type', models.CharField(max_length=255)),
                ('chnnel', models.CharField(max_length=255)),
                ('charge_code', models.IntegerField()),
                ('assistant', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('compliment', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_yn', models.CharField(max_length=255)),
                ('etc_1', models.CharField(blank=True, max_length=255, null=True)),
                ('red_dt', models.DateTimeField(blank=True, null=True)),
                ('eit_dt', models.DateTimeField(blank=True, null=True)),
                ('reg_id', models.DateTimeField(blank=True, null=True)),
                ('group_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('nm_kr', models.CharField(blank=True, max_length=255, null=True)),
                ('nm_en', models.CharField(blank=True, max_length=255, null=True)),
                ('r_p_a_choose', models.CharField(blank=True, max_length=255, null=True)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('use_yn', models.IntegerField()),
                ('requester_id', models.IntegerField(blank=True, null=True)),
                ('red_dt', models.DateTimeField(blank=True, null=True)),
                ('eit_dt', models.DateTimeField(blank=True, null=True)),
                ('reg_id', models.DateTimeField(blank=True, null=True)),
                ('group_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('nm_kr', models.CharField(blank=True, max_length=255, null=True)),
                ('nm_en', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_code', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('use_yn', models.IntegerField()),
                ('red_dt', models.DateTimeField(blank=True, null=True)),
                ('eit_dt', models.DateTimeField(blank=True, null=True)),
                ('reg_id', models.DateTimeField(blank=True, null=True)),
                ('group_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockComeR',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('nm_kr', models.CharField(blank=True, max_length=255, null=True)),
                ('nm_en', models.CharField(blank=True, max_length=255, null=True)),
                ('ea', models.IntegerField()),
                ('income_dt', models.DateTimeField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('up_key', models.IntegerField(blank=True, null=True)),
                ('standard_bundle', models.IntegerField(blank=True, null=True)),
                ('bundle', models.IntegerField(blank=True, null=True)),
                ('red_dt', models.DateTimeField(blank=True, null=True)),
                ('eit_dt', models.DateTimeField(blank=True, null=True)),
                ('reg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group_key', models.IntegerField(blank=True, null=True)),
                ('use_yn', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'stock_come_r',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockOutR',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('nm_kr', models.CharField(blank=True, max_length=255, null=True)),
                ('nm_en', models.CharField(blank=True, max_length=255, null=True)),
                ('ea', models.IntegerField()),
                ('out_dt', models.DateTimeField(blank=True, null=True)),
                ('red_dt', models.DateTimeField(blank=True, null=True)),
                ('eit_dt', models.DateTimeField(blank=True, null=True)),
                ('reg_id', models.DateTimeField(blank=True, null=True)),
                ('group_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_out_r',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('nm_kr', models.CharField(blank=True, max_length=255, null=True)),
                ('nm_en', models.CharField(blank=True, max_length=255, null=True)),
                ('use_yn', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('red_dt', models.DateTimeField(blank=True, null=True)),
                ('eit_dt', models.DateTimeField(blank=True, null=True)),
                ('reg_id', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
